### ISSUE TITLE
刷入失败

### ISSUE THREAD

**Issue by fantuyuan** [Magisk-Modules-Repo/MiPushFake#2]
- Copying zip to temp directory
- Installing MiPushFake.zip
***********************************
! /data/magisk isn't setup properly!
! Please install Magisk v13.1+!
***********************************
! Installation failed

oneplus3 
Android 8.0
magisk v17.1

**Comment by fantuyuan** [comment]
已解决。

名称为：XiaoMi Push Framework Fake

**Comment by daxinnan** [comment]
新的名称为 XiaoMi Push Framework Fake Advanced.

**Comment by jianzhao0806** [comment]
现在还有维护吗，为啥上面提到的搜索不出来

**Comment by cubesky** [comment]
不再维护 请使用 Riru 版本的插件
