### ISSUE TITLE
Maybe add brand and manufacture can match some other software use mipushcore

### ISSUE THREAD

**Issue by JohnnySun** [Magisk-Modules-Repo/MiPushFake#3]
Change this to build.prop:
ro.product.brand=Xiaomi
ro.product.manufacturer=Xiaomi

some software use brand and manufacture to check a device is XiaoMi or others. add this to build.prop, we can mach some other apps use core to push message( Like Tieba, Mafengwo, TapTap, and others)

**Comment by cubesky** [comment]
These two prop will break some feature provide by other rom such as H2OS Bus Card

**Comment by JohnnySun** [comment]
yep, may some rom also use this prop to enable some func

**Comment by JohnnySun** [comment]
so maybe the best way is uses xposed, return difference value for system apps and user apps
